#pragma once
void graph_test(const Args &args) {
    args.allow({"out"});
    fs::path out = args.get("out", "reports/graph-tests");
    fs::create_directories(out);
    Config q{32, 64, 2};
    Model regular(q, 1, 1), captured(q, 1, 1), learner(q, 1, 8);
    auto w = initialize(q, regular.a, 127);
    regular.w.put(w);
    captured.w.put(w);
    learner.share_parameters(captured);
    std::vector<float> state(q.h * q.l);
    for (size_t i = 0; i < state.size(); ++i)
        state[i] = .7f * std::sin(float(i));
    regular.membranes(state);
    captured.membranes(state);
    GraphDecoder decoder(captured);
    require(maxdiff(state, captured.membranes()) == 0, "Graph capture changed live state");
    float error = 0;
    for (int i = 0; i < 64; ++i) {
        int byte = (i * 37 + 19) % 256;
        regular.forward({byte}, nullptr, true);
        error = std::max(error, maxdiff(regular.logits.host(), decoder.step(byte)));
        error = std::max(error, maxdiff(regular.membranes(), captured.membranes()));
    }
    auto before = captured.w.host();
    std::vector<int> x{19, 56, 93, 130, 167, 204, 241, 22}, y{56, 93, 130, 167, 204, 241, 22, 59};
    learner.forward(x, &y);
    learner.backward();
    learner.update(1, .003f);
    decoder.begin(); // Learn -> speak handoff using shared weights, without recapture.
    require(maxdiff(before, captured.w.host()) > .0001f, "Graph test did not change weights");
    regular.w.put(captured.w.host());
    auto next = decoder.step(59);
    regular.forward({59}, nullptr, true);
    error = std::max(error, maxdiff(next, regular.logits.host()));
    error = std::max(error, maxdiff(regular.membranes(), captured.membranes()));
    require(error < 3e-5f, "Captured inference differs or reads stale weights");
    std::ofstream f(out / "native.json");
    f << "{\"passed\":true,\"max_error\":" << error
      << ",\"capture_preserves_state\":true,\"sees_live_weight_updates\":true}\n";
    std::cout << "PASS graph: state preserved, logits/state match, live updates visible. Max error " << error
              << "\n";
}

// Wall-clock decode includes CPU top-k sampling, byte H2D, model execution,
// logits D2H and synchronization. Capture/setup and console/file I/O are excluded.
void decode_bench(const Args &args) {
    args.allow({"checkpoint", "out", "tokens", "rounds", "prompt", "fast"});
    auto path = args.get("checkpoint");
    State s = header(path);
    Config q = checkpoint_config(s);
    Model regular(q, 1, 1), captured(q, 1, 1);
    load(path, regular, s);
    captured.w.share(regular.w);
    bool fast = !args.get("fast").empty();
    regular.fast(fast);
    captured.fast(fast);
    int count = args.num("tokens", 512), rounds = args.num("rounds", 5);
    auto prompt = args.get("prompt", "The bird ");
    require(count > 0 && count <= 100000 && rounds >= 2 && rounds <= 100 && !prompt.empty(),
            "Invalid decode benchmark limits");
    auto start = std::chrono::steady_clock::now();
    GraphDecoder graph(captured);
    double setup =
        std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - start).count();
    std::array<std::vector<double>, 2> us;
    std::array<std::string, 2> generated;
    float error = 0;
    // One untimed warm-up, then alternating ordering to reduce ordering bias.
    for (int round = -1; round < rounds; ++round) {
        for (int pass = 0; pass < 2; ++pass) {
            int mode = (pass + (round < 0 ? 0 : round % 2)) % 2;
            Model &m = mode ? captured : regular;
            m.reset();
            graph.begin();
            auto step = [&](int byte) {
                if (mode)
                    return graph.step(byte);
                m.forward({byte}, nullptr, true);
                return m.logits.host();
            };
            std::vector<float> logits;
            for (unsigned char byte : prompt)
                logits = step(byte);
            uint64_t rng = 42;
            std::string text;
            start = std::chrono::steady_clock::now();
            for (int t = 0; t < count; ++t) {
                int byte = draw_byte(logits, 40, .8f, rng);
                text.push_back(char(byte));
                logits = step(byte);
            }
            double duration =
                std::chrono::duration<double, std::micro>(std::chrono::steady_clock::now() - start).count();
            if (round >= 0)
                us[mode].push_back(duration / count);
            generated[mode] = text;
        }
        require(generated[0] == generated[1], "Graph changed generated bytes during benchmark");
        error = std::max(error, maxdiff(regular.membranes(), captured.membranes()));
        error = std::max(error, maxdiff(regular.logits.host(), captured.logits.host()));
    }
    std::array<double, 2> median;
    for (int i = 0; i < 2; ++i) {
        auto sorted = us[i];
        std::sort(sorted.begin(), sorted.end());
        median[i] = sorted.size() % 2 ? sorted[sorted.size() / 2]
                                      : (sorted[sorted.size() / 2 - 1] + sorted[sorted.size() / 2]) * .5;
    }
    fs::path out = args.get("out", "reports/decode");
    fs::create_directories(out);
    dump(out / "sample.txt", std::vector<char>(generated[1].begin(), generated[1].end()));
    std::ofstream f(out / "benchmark.json");
    f << std::setprecision(10) << "{\"parameters\":" << regular.a.n << ",\"tokens_per_round\":" << count
      << ",\"rounds\":" << rounds << ",\"fast_math\":" << (fast ? "true" : "false")
      << ",\"graph_setup_ms\":" << setup << ",\"regular_us_per_byte\":" << median[0]
      << ",\"graph_us_per_byte\":" << median[1] << ",\"speedup\":" << median[0] / median[1]
      << ",\"generated_bytes_identical\":true,\"state_logits_max_error\":" << error;
    for (int i = 0; i < 2; ++i) {
        f << (i ? ",\"graph_rounds_us\":[" : ",\"regular_rounds_us\":[");
        for (size_t j = 0; j < us[i].size(); ++j)
            f << (j ? "," : "") << us[i][j];
        f << "]";
    }
    f << "}\n";
    std::cout << "decode regular_us=" << median[0] << " graph_us=" << median[1]
              << " speedup=" << median[0] / median[1] << " identical_bytes=yes error=" << error << "\n";
}
