// Frozen teacher execution on an observed replay window. Padded suffixes bound
// teacher scratch space; only the causal prefix supplies teacher targets.
#pragma once
namespace teachers {
class Replay {
    int chunk_;
    std::vector<std::unique_ptr<Model>> models_;
    distillation::Targets targets_;
  public:
    uint64_t gpu_bytes = 0, budget_bytes = 0, free_before_bytes = 0;
    static uint64_t required_bytes(const Bundle &bundle, int chunk) {
        uint64_t bytes = uint64_t(chunk) * 257 * sizeof(float);
        for (size_t i = 0; i < bundle.identity.count(); ++i)
            bytes += model_working_bytes(bundle.identity.config(i), 1, chunk, ModelBuffers::frozen_forward);
        return bytes;
    }
    static void check_budget(const Bundle &bundle, int chunk, uint64_t budget, uint64_t &free_bytes) {
        size_t available, total;
        ck(cudaMemGetInfo(&available, &total));
        free_bytes = available;
        uint64_t required = required_bytes(bundle, chunk), reserve = 64ull * 1024 * 1024;
        require(required <= budget && available > reserve && required <= available - reserve,
                "Teacher memory budget exhausted or insufficient free GPU memory");
    }
    static std::unique_ptr<Replay> create(Bundle &bundle, int chunk, uint64_t budget) {
        uint64_t available;
        check_budget(bundle, chunk, budget, available);
        return std::unique_ptr<Replay>(new Replay(bundle, chunk, budget, available));
    }
  private:
    Replay(Bundle &bundle, int chunk, uint64_t budget, uint64_t available)
        : chunk_(chunk), targets_(chunk, bundle.identity.temperature()),
          gpu_bytes(required_bytes(bundle, chunk)), budget_bytes(budget), free_before_bytes(available) {
        for (size_t i = 0; i < bundle.identity.count(); ++i) {
            auto model = std::make_unique<Model>(bundle.identity.config(i), 1, chunk, ModelBuffers::frozen_forward);
            model->w.put(bundle.weights[i]);
            model->reset();
            // Frozen teacher targets use strict FP32, independent of learner TF32.
            model->fast(false);
            models_.push_back(std::move(model));
        }
        bundle.weights.clear();
    }
  public:
    distillation::Result apply(Model &learner, const std::vector<int> &input,
                               const std::vector<float> &weights, State &s) {
        require(input.size() == size_t(learner.N) && input.size() <= size_t(chunk_), "Teacher replay shape differs");
        auto padded = input;
        padded.resize(size_t(chunk_), 0);
        for (auto &model : models_)
            model->forward(padded); // Reset-state replay, no generated bytes or live recurrence.
        targets_.set_rows(int(input.size()));
        targets_.from_logits(models_[0]->logits, models_.size() == 2 ? &models_[1]->logits : nullptr,
                             s.teaching.mixture(), true);
        auto result = targets_.apply(learner, s.teaching.strength(), weights);
        ++s.teaching.words[9];
        s.teaching.words[10] += input.size();
        return result;
    }
};
void report(std::ostream &out, const State &s, const Replay *runtime, uint64_t budget) {
    if (s.meta[17] != 6)
        return;
    const auto &p = s.teaching;
    out << ",\"teaching_active\":" << (p.active() ? "true" : "false")
        << ",\"teacher_bundle_hash\":\"" << p.words[4] << "\",\"teacher_source_hash\":\"" << p.words[5]
        << "\",\"teacher_eligible_documents\":" << p.words[6] << ",\"teacher_count\":" << p.count()
        << ",\"teacher_updates\":" << p.words[9] << ",\"teacher_pairs\":" << p.words[10]
        << ",\"teacher_temperature\":" << p.temperature() << ",\"teacher_strength\":" << p.strength()
        << ",\"teacher_mixture\":" << p.mixture() << ",\"teacher_population_scope\":" << p.words[14]
        << ",\"teacher_extra_gpu_bytes\":" << (runtime ? runtime->gpu_bytes : 0)
        << ",\"teacher_budget_bytes\":" << budget
        << ",\"teacher_free_before_bytes\":" << (runtime ? runtime->free_before_bytes : 0)
        << ",\"teacher_math\":\"strict_fp32\",\"teacher_targets_from_observed_replay_only\":true";
}
} // namespace teachers
