'use strict';
const $ = id => document.getElementById(id);
let token = '', active = null, busy = false, models = [];
const element = (tag, cls, content) => { const n=document.createElement(tag); n.className=cls; if(content!==undefined)n.textContent=content; return n; };
function error(message){$('error').hidden=!message;$('error').textContent=message||'';}
function controls(){for(const id of ['load','save','ask','teach','model','passes']) $(id).disabled=busy||(['save','ask','teach'].includes(id)&&!active);document.querySelectorAll('.session-link').forEach(b=>b.disabled=busy);$('status-dot').classList.toggle('busy',busy);}
async function api(path,body){const res=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Token':token},body:JSON.stringify(body)}:{});const data=await res.json();if(!res.ok)throw Error(data.error||'Request failed');return data;}
function render(session){active=session;controls();if(!session)return;$('model-badge').textContent=session.model;$('turn-count').textContent=session.messages.length+' responses';const list=$('messages');list.replaceChildren();for(const row of session.messages){const item=element('article','message');item.append(element('div','message-head','YOU'),element('p','question-bubble',row.question),element('div','message-head','SYNAPTICGENESIS'),element('p','answer-text',row.text));const actions=element('div','answer-actions');const correct=element('button','correct-button','Correct this answer');correct.type='button';correct.onclick=()=>{$('teach-question').value=row.question;$('teach-answer').value='';$('teach-answer').focus();};actions.append(correct,element('span','',Math.round(row.resident_decode_bytes_per_second)+' bytes/s · '+row.generated_bytes+' bytes'));item.append(actions);const detail=element('details','');detail.append(element('summary','','Raw output & timing'),element('pre','',JSON.stringify({valid_utf8:row.valid_utf8,raw_hex:row.raw_hex,prefill_seconds:row.prefill_seconds,decode_seconds:row.decode_seconds,capture_seconds:row.capture_seconds},null,2)));item.append(detail);list.append(item);}list.scrollTop=list.scrollHeight;const last=session.corrections.at(-1);$('last-learning').textContent=last?.state==='learned'?'Last correction saved · '+last.passes+' passes · '+last.metrics.seconds.toFixed(2)+'s learning':'';}
function renderSessions(rows){const list=$('sessions');list.replaceChildren();if(!rows.length)list.append(element('p','muted','Your sessions will appear here.'));for(const row of rows){const b=element('button','session-link',row.model);b.append(element('small','',new Date(row.created_utc).toLocaleString()+' · '+row.messages+' responses'));b.onclick=()=>run('resume',{session:row.id},'Restoring saved session…');list.append(b);}controls();}
async function refresh(){const s=await api('state');token=s.token;models=s.models;if(!$('model').options.length){for(const m of models){const o=element('option','',m.name+(m.available?'':' · unavailable'));o.value=m.id;o.disabled=!m.available;$('model').append(o);}const first=models.find(m=>m.available);if(first)$('model').value=first.id;description();}renderSessions(s.sessions);$('status').textContent=s.status;return s;}
function description(){const m=models.find(m=>m.id===$('model').value);$('model-description').textContent=m?.description||'';}
async function run(action,body,label){if(busy)return;busy=true;error('');controls();$('status').textContent=label;try{const {job}=await api(action,body);for(;;){await new Promise(r=>setTimeout(r,500));const result=await api('jobs/'+job);if(result.state==='failed')throw Error(result.error);if(result.state==='complete'){render(result.result);break;}const state=await api('state');$('status').textContent=state.status;}await refresh();}catch(e){error(e.message);$('status').textContent='Operation failed — load or resume to recover';}finally{busy=false;controls();}}
$('model').onchange=description;$('load').onclick=()=>run('load',{model:$('model').value},'Loading model…');$('save').onclick=()=>run('save',{},'Saving checkpoint…');$('ask-form').onsubmit=e=>{e.preventDefault();const question=$('question').value.trim();if(!question)return;run('ask',{question},'Generating answer…');$('question').value='';};$('question').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!busy&&active)$('ask-form').requestSubmit();}};$('teach-form').onsubmit=e=>{e.preventDefault();const question=$('teach-question').value.trim(),answer=$('teach-answer').value.trim();if(!question||!answer){error('Enter both a question and its corrected answer.');return;}run('teach',{question,answer,passes:Number($('passes').value)},'Preparing correction…');};document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{$('question').value=b.dataset.question;$('question').focus();});refresh().then(s=>render(s.session)).catch(()=>{error('Start the local Studio server to connect to your C++/CUDA models. See docs/live-studio.md on GitHub.');$('status').textContent='Local runtime offline';$('load').disabled=true;});
